### ISSUE TITLE
Migrate images to Github

### ISSUE THREAD

**Issue by arturocuya** [rokucommunity/rokucommunity.github.io#3]
Currently all images are hosted in Cloudinary, a 3rd party service in which I created an account and used the free plan. This is not necessary. Images can be "hosted" by pasting them in a Github issue and copying the generated link. It's not CDN but it's good enough.

All website images are attached here: [website-images.zip](https://github.com/rokucommunity/rokucommunity.github.io/files/9845782/website-images.zip)

We should probably create a helper object to only reference image sources as names, in case we need to change a URL.

```js
// src/images.js
export default {
    "logo": {
        "href": "https://github.com/.../images/.../logo.png",
        "alt": "Our logo"
    }
}
```

```astro
---
import images from "src/images.js"
---
<img href={images.logo.href} alt={images.logo.alt}/>
```

**Comment by TwitchBronBron** [comment]
Resolved by #10
